<?php
    session_start();
    if(isset($_SESSION['email']))
    {
        session_destroy();
        header('location:../login/login.php');
    }
    else
    {
        header('location:../login/login.php');
    }
?>